### PR TITLE
Update OWNERS file

### PR DESCRIPTION
**Pull request by hardys**
Remove russellb as his area of focus has changed, add
stbenjam and derekhiggins who have both contributed here and
to the downstream fork and will be familiar enough to approve.

### CODE REVIEW

**Comment by hardys** [comment]
/cc @russellb @derekhiggins @stbenjam

We can add more approvers as necessary but I wanted to update this so we don't get blocked with only two people able to merge PRs :)

**Comment by derekhiggins** [comment]
> /cc @russellb @derekhiggins @stbenjam
> 
> We can add more approvers as necessary but I wanted to update this so we don't get blocked with only two people able to merge PRs :)

/lgtm

**Comment by derekhiggins** [comment]
> @derekhiggins: adding LGTM is restricted to approvers and reviewers in OWNERS files.

:-)

**Pull request merged**
